name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CSV_URL: "MLproject/train_pca.csv"

jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    # Save models to GitHub Repository
      - name: Save mlruns to repo
        run: |
          git config --global user.name "RizkiYanuar-Tech"
          git config --global user.email "ryanuar83@gmail.com"
          git add mlruns/
          git commit -m "Save mlruns from CI run"
          git push origin master
